name: Bulk import repos pipeline

on:
  workflow_dispatch:

jobs:
  bulk-import-repos:
    uses: G-Research/github-terraformer/.github/workflows/bulk-import.yaml@gr-oss-1125-resolve-integration-id-to-source-name
    with:
      gcss_ref: gr-oss-1125-resolve-integration-id-to-source-name
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}