name: Bulk import repos pipeline

on:
  workflow_dispatch:

jobs:
  bulk-import-repos:
    uses: G-Research/github-terraformer/.github/workflows/bulk-import.yaml@upgrade-terraform-terraform-provider-version
    with:
      gcss_ref: upgrade-terraform-terraform-provider-version
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}