name: Bulk import repos pipeline

on:
  workflow_dispatch:

jobs:
  bulk-import-repos:
    uses: G-Research/github-terraformer/.github/workflows/bulk-import.yaml@fix-master-branch-bug
    with:
      gcss_ref: fix-master-branch-bug
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}