name: Bulk import repos pipeline

on:
  workflow_dispatch:

jobs:
  bulk-import-repos:
    uses: G-Research/github-terraformer/.github/workflows/bulk-import.yaml@v0.0.1
    with:
      gcss_ref: v0.0.1
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}