name: Terraform apply

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'importer_tmp_dir/**'

jobs:
  terraform-apply:
    uses: G-Research/github-terraformer/.github/workflows/tf-apply.yaml@fix-master-branch-bug
    with:
      commit_sha: ${{ github.sha }}
      gcss_ref: fix-master-branch-bug
      tfc_org: "GR-OSS"
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      tfc_token: ${{ secrets.TFC_TOKEN }}